import { describe, it, expect } from "vitest";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import config from "../../vite.config.js";
import { BOOKING_ROOT_EXCLUSIONS } from "../../scripts/lib/combined-output.mjs";

// The booking app and the marketing website (website/) are separate builds that
// are served from one origin, so anything either one emits at the root of the
// deployment can silently overwrite the other's file of the same name. The
// dangerous case is robots.txt: the booking app's says `Disallow: /`, so if it
// won at the root it would tell Google to drop the whole marketing site.
//
// The fix is that the booking app emits nothing at the root except a short,
// deliberate list — everything else lives under /app/. These tests pin that.

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");

/** Files the booking app must keep at the deployment root, and why. */
const BOOKING_ROOT_PUBLIC_FILES = new Set([
  // A service worker can only claim a scope at or below its own directory, so
  // the push handler has to sit at the root to be usable by /staff/.
  "push-sw.js",
  // Kept only so the standalone smarterdog.vercel.app deployment stays
  // un-indexed. The merged deployment publishes the website's robots.txt.
  "robots.txt",
]);

function filesUnder(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    if (entry.name === ".DS_Store") return [];
    const full = path.join(dir, entry.name);
    return entry.isDirectory() ? filesUnder(full) : [full];
  });
}

describe("static output namespace", () => {
  it("keeps every booking static file under public/app/ bar the documented roots", () => {
    const publicDir = path.join(repoRoot, "public");
    const stray = filesUnder(publicDir)
      .map((f) => path.relative(publicDir, f))
      .filter((rel) => !rel.startsWith(`app${path.sep}`))
      .filter((rel) => !BOOKING_ROOT_PUBLIC_FILES.has(rel));
    expect(stray).toEqual([]);
  });

  it("emits hashed build assets under the same namespace", () => {
    // Without this the booking app writes /assets/, which is exactly where the
    // website writes its own hashed output and its photography.
    expect(config.build?.assetsDir).toMatch(/^app\//);
  });

  it("points every root-absolute asset URL at /app/", () => {
    const sources = ["index.html", "src/index.css"];
    const offenders: string[] = [];
    for (const rel of sources) {
      const text = fs.readFileSync(path.join(repoRoot, rel), "utf8");
      for (const [, url] of text.matchAll(/["'(](\/[^"')\s]+\.(?:png|svg|jpg|webp|woff2|json))/g)) {
        if (!url.startsWith("/app/")) offenders.push(`${rel}: ${url}`);
      }
    }
    expect(offenders).toEqual([]);
  });

  it("holds the collision surface to what the merge deliberately resolves", () => {
    // The merge drops exactly these two from the booking build: the website's
    // robots.txt and index.html win at the root, and the booking shell is
    // served from /app/index.html instead. Anything else appearing here would
    // be one app silently overwriting the other.
    const websitePublic = path.join(repoRoot, "website", "public");
    const websiteRoot = new Set([
      ...fs.readdirSync(websitePublic).filter((n) => n !== ".DS_Store"),
      "index.html",
      "assets",
    ]);
    const bookingRoot = new Set([
      ...BOOKING_ROOT_PUBLIC_FILES,
      "index.html",
      // generated by vite-plugin-pwa (plus a hash-named workbox-*.js, which
      // cannot collide by construction)
      "sw.js",
      "registerSW.js",
    ]);
    const collisions = [...bookingRoot].filter((n) => websiteRoot.has(n)).sort();
    expect(collisions).toEqual([...BOOKING_ROOT_EXCLUSIONS].sort());
  });
});
