// Renders public/app/icons/app-icon.svg to PNGs at the sizes iOS / Android / PWA need.
// Usage: node scripts/render-icons.mjs
//
// Output:
//   public/app/apple-touch-icon.png            (180x180)
//   public/app/icons/apple-touch-icon-180.png  (180x180, mirror for explicit reference)
//   public/app/icons/icon-192.png              (192x192)
//   public/app/icons/icon-512.png              (512x512)
//   public/app/icons/icon-1024.png             (1024x1024, master)

import { chromium } from 'playwright';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import fs from 'node:fs';
import crypto from 'node:crypto';

const sha256 = (buf) => crypto.createHash('sha256').update(buf).digest('hex');

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');
const publicDir = path.join(repoRoot, 'public', 'app');
const iconsDir = path.join(publicDir, 'icons');
const svgPath = path.join(iconsDir, 'app-icon.svg');
const lockPath = path.join(iconsDir, 'icons.lock.json');
const playwrightVersion = JSON.parse(
  fs.readFileSync(path.join(repoRoot, 'package.json'), 'utf8'),
).devDependencies?.['@playwright/test'] ?? 'unknown';

const svg = fs.readFileSync(svgPath, 'utf8');

const targets = [
  { out: path.join(publicDir, 'apple-touch-icon.png'),         size: 180 },
  { out: path.join(iconsDir,  'apple-touch-icon-180.png'),     size: 180 },
  { out: path.join(iconsDir,  'icon-192.png'),                 size: 192 },
  { out: path.join(iconsDir,  'icon-512.png'),                 size: 512 },
  { out: path.join(iconsDir,  'icon-1024.png'),                size: 1024 },
];

const html = (size) => `<!doctype html>
<html>
<head>
<meta charset="utf-8">
<style>
  html, body { margin: 0; padding: 0; background: transparent; }
  body { width: ${size}px; height: ${size}px; }
  svg { display: block; width: ${size}px; height: ${size}px; }
</style>
</head>
<body>
${svg}
</body>
</html>`;

// Browser resolution, in order: an explicit override, then Playwright's own
// download. The explicit path used to be hardcoded to a pinned sandbox build,
// which broke on any Playwright bump and meant CI could not run this at all —
// so `npm run check:icons` could never prove the committed PNGs came from the
// committed SVG. Both variable names are honoured: PLAYWRIGHT_CHROMIUM_EXECUTABLE
// is the one playwright.config.ts and CLAUDE.md document, PW_CHROMIUM_PATH is
// kept so existing local setups keep working.
const explicitChromium =
  process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE || process.env.PW_CHROMIUM_PATH || null;
if (explicitChromium && !fs.existsSync(explicitChromium)) {
  throw new Error(
    `Chromium override points at a file that does not exist: ${explicitChromium}\n` +
      'Unset PLAYWRIGHT_CHROMIUM_EXECUTABLE / PW_CHROMIUM_PATH to use the bundled browser.',
  );
}
const browser = await chromium.launch(
  explicitChromium ? { executablePath: explicitChromium } : {},
);
try {
  const context = await browser.newContext({ baseURL: 'http://localhost:0' });
  for (const { out, size } of targets) {
    const page = await context.newPage();
    await page.setViewportSize({ width: size, height: size });
    await page.route('**/*', async (route) => {
      const url = new URL(route.request().url());
      if (url.pathname.startsWith('/fonts/')) {
        const fp = path.join(publicDir, url.pathname);
        if (fs.existsSync(fp)) {
          return route.fulfill({ status: 200, body: fs.readFileSync(fp), headers: { 'content-type': 'font/woff2' } });
        }
      }
      return route.continue();
    });
    await page.setContent(html(size), { waitUntil: 'networkidle' });
    await page.evaluate(() => document.fonts.ready);
    const buf = await page.locator('svg').screenshot({ omitBackground: true });
    fs.writeFileSync(out, buf);
    await page.close();
    console.log(`wrote ${path.relative(repoRoot, out)} (${size}x${size}, ${buf.length} bytes)`);
  }
  // Provenance. Written only here, from this run, so the source hash and the
  // output hashes can never describe different renders. check:icons verifies
  // every field; in CI, where the Chromium build matches, it also re-renders
  // and byte-compares (rendering is deterministic for a fixed build).
  const lock = {
    $comment:
      'Generated by scripts/render-icons.mjs. Do not hand-edit — run `npm run icons:build`.',
    source: {
      path: path.relative(repoRoot, svgPath),
      sha256: sha256(fs.readFileSync(svgPath)),
    },
    renderer: {
      chromium: browser.version(),
      playwright: playwrightVersion,
    },
    outputs: targets.map(({ out, size }) => ({
      path: path.relative(repoRoot, out),
      sha256: sha256(fs.readFileSync(out)),
      width: size,
      height: size,
    })),
  };
  fs.writeFileSync(lockPath, `${JSON.stringify(lock, null, 2)}\n`);
  console.log(`wrote ${path.relative(repoRoot, lockPath)}`);
} finally {
  await browser.close();
}
